# This file is auto-generated. Do not edit manually.

rev_dict = {'A Thousand Cuts': ['A_Thousand_Cuts'],
 'AI': ['Creative_AI'],
 'AThousandCuts': ['A_Thousand_Cuts'],
 'Accuracy': ['Accuracy'],
 'Acrobatics': ['Acrobatics'],
 'Adrenaline': ['Adrenaline'],
 'After Image': ['After_Image'],
 'AfterImage': ['After_Image'],
 'Aggregate': ['Aggregate'],
 'Alchemize': ['Alchemize'],
 'All for One': ['All_for_One'],
 'All-Out Attack': ['All-Out_Attack'],
 'AllOutAttack': ['All-Out_Attack'],
 'AllforOne': ['All_for_One'],
 'Alpha': ['Alpha'],
 'Amplify': ['Amplify'],
 'Anger': ['Anger'],
 'Apotheosis': ['Apotheosis'],
 'Apparition': ['Apparition'],
 'Armaments': ['Armaments'],
 "Ascender's Bane": ["Ascender's_Bane"],
 'AscendersBane': ["Ascender's_Bane"],
 'Auto-Shields': ['Auto-Shields'],
 'AutoShields': ['Auto-Shields'],
 'Backflip': ['Backflip'],
 'Backstab': ['Backstab'],
 'Ball Lightning': ['Ball_Lightning'],
 'BallLightning': ['Ball_Lightning'],
 'Bandage Up': ['Bandage_Up'],
 'BandageUp': ['Bandage_Up'],
 'Bane': ['Bane'],
 'Barrage': ['Barrage'],
 'Barricade': ['Barricade'],
 'Bash': ['Bash'],
 'Battle Hymn': ['Battle_Hymn'],
 'Battle Trance': ['Battle_Trance'],
 'BattleHymn': ['Battle_Hymn'],
 'BattleTrance': ['Battle_Trance'],
 'Beam Cell': ['Beam_Cell'],
 'BeamCell': ['Beam_Cell'],
 'Berserk': ['Berserk'],
 'Beta': ['Beta'],
 'Biased Cognition': ['Biased_Cognition'],
 'BiasedCognition': ['Biased_Cognition'],
 'Bite': ['Bite'],
 'Blade Dance': ['Blade_Dance'],
 'BladeDance': ['Blade_Dance'],
 'Blasphemy': ['Blasphemy'],
 'Blind': ['Blind'],
 'Blizzard': ['Blizzard'],
 'Blood for Blood': ['Blood_for_Blood'],
 'BloodforBlood': ['Blood_for_Blood'],
 'Bloodletting': ['Bloodletting'],
 'Bludgeon': ['Bludgeon'],
 'Blur': ['Blur'],
 'Body Slam': ['Body_Slam'],
 'BodySlam': ['Body_Slam'],
 'Boot Sequence': ['Boot_Sequence'],
 'BootSequence': ['Boot_Sequence'],
 'Bouncing Flask': ['Bouncing_Flask'],
 'BouncingFlask': ['Bouncing_Flask'],
 'Bowling Bash': ['Bowling_Bash'],
 'BowlingBash': ['Bowling_Bash'],
 'Brilliance': ['Brilliance'],
 'Brutality': ['Brutality'],
 'Buffer': ['Buffer'],
 'Bullet Time': ['Bullet_Time'],
 'BulletTime': ['Bullet_Time'],
 'Bullseye': ['Bullseye'],
 'Burn': ['Burn'],
 'Burning Pact': ['Burning_Pact'],
 'BurningPact': ['Burning_Pact'],
 'Burst': ['Burst'],
 'Calculated Gamble': ['Calculated_Gamble'],
 'CalculatedGamble': ['Calculated_Gamble'],
 'Caltrops': ['Caltrops'],
 'Capacitor': ['Capacitor'],
 'Carnage': ['Carnage'],
 'Carve Reality': ['Carve_Reality'],
 'CarveReality': ['Carve_Reality'],
 'Catalyst': ['Catalyst'],
 'Chaos': ['Chaos'],
 'Charge Battery': ['Charge_Battery'],
 'ChargeBattery': ['Charge_Battery'],
 'Chill': ['Chill'],
 'Choke': ['Choke'],
 'Chrysalis': ['Chrysalis'],
 'Clash': ['Clash'],
 'Claw': ['Claw'],
 'Cleave': ['Cleave'],
 'Cloak and Dagger': ['Cloak_and_Dagger'],
 'CloakandDagger': ['Cloak_and_Dagger'],
 'Clothesline': ['Clothesline'],
 'Clumsy': ['Clumsy'],
 'Cold Snap': ['Cold_Snap'],
 'ColdSnap': ['Cold_Snap'],
 'Collect': ['Collect'],
 'Combust': ['Combust'],
 'Compile Driver': ['Compile_Driver'],
 'CompileDriver': ['Compile_Driver'],
 'Concentrate': ['Concentrate'],
 'Conclude': ['Conclude'],
 'Conjure Blade': ['Conjure_Blade'],
 'ConjureBlade': ['Conjure_Blade'],
 'Consecrate': ['Consecrate'],
 'Consume': ['Consume'],
 'Coolheaded': ['Coolheaded'],
 'Core Surge': ['Core_Surge'],
 'CoreSurge': ['Core_Surge'],
 'Corpse Explosion': ['Corpse_Explosion'],
 'CorpseExplosion': ['Corpse_Explosion'],
 'Corruption': ['Corruption'],
 'Creative AI': ['Creative_AI'],
 'CreativeAI': ['Creative_AI'],
 'Crescendo': ['Crescendo'],
 'Crippling Cloud': ['Crippling_Cloud'],
 'CripplingCloud': ['Crippling_Cloud'],
 'Crush Joints': ['Crush_Joints'],
 'CrushJoints': ['Crush_Joints'],
 'Curse of the Bell': ['Curse_of_the_Bell'],
 'CurseoftheBell': ['Curse_of_the_Bell'],
 'Cut Through Fate': ['Cut_Through_Fate'],
 'CutThroughFate': ['Cut_Through_Fate'],
 'DNA': ['Genetic_Algorithm'],
 'Dagger Spray': ['Dagger_Spray'],
 'Dagger Throw': ['Dagger_Throw'],
 'DaggerSpray': ['Dagger_Spray'],
 'DaggerThrow': ['Dagger_Throw'],
 'Dark Embrace': ['Dark_Embrace'],
 'Dark Shackles': ['Dark_Shackles'],
 'DarkEmbrace': ['Dark_Embrace'],
 'DarkShackles': ['Dark_Shackles'],
 'Darkness': ['Darkness'],
 'Dash': ['Dash'],
 'Dazed': ['Dazed'],
 'Deadly Poison': ['Deadly_Poison'],
 'DeadlyPoison': ['Deadly_Poison'],
 'Decay': ['Decay'],
 'Deceive Reality': ['Deceive_Reality'],
 'DeceiveReality': ['Deceive_Reality'],
 'Deep Breath': ['Deep_Breath'],
 'DeepBreath': ['Deep_Breath'],
 'Defend': ['Defend_(Defect)', 'Defend_(Ironclad)', 'Defend_(Silent)', 'Defend_(Watcher)'],
 'Defend (Defect)': ['Defend_(Defect)'],
 'Defend (Ironclad)': ['Defend_(Ironclad)'],
 'Defend (Silent)': ['Defend_(Silent)'],
 'Defend (Watcher)': ['Defend_(Watcher)'],
 'Deflect': ['Deflect'],
 'Defragment': ['Defragment'],
 'Demon Form': ['Demon_Form'],
 'DemonForm': ['Demon_Form'],
 'Deus Ex Machina': ['Deus_Ex_Machina'],
 'DeusExMachina': ['Deus_Ex_Machina'],
 'Deva Form': ['Deva_Form'],
 'DevaForm': ['Deva_Form'],
 'Devotion': ['Devotion'],
 'Die Die Die': ['Die_Die_Die'],
 'DieDieDie': ['Die_Die_Die'],
 'Disarm': ['Disarm'],
 'Discovery': ['Discovery'],
 'Distraction': ['Distraction'],
 'Dodge and Roll': ['Dodge_and_Roll'],
 'DodgeandRoll': ['Dodge_and_Roll'],
 'Doom and Gloom': ['Doom_and_Gloom'],
 'DoomandGloom': ['Doom_and_Gloom'],
 'Doppelganger': ['Doppelganger'],
 'Double Energy': ['Double_Energy'],
 'Double Tap': ['Double_Tap'],
 'DoubleEnergy': ['Double_Energy'],
 'DoubleTap': ['Double_Tap'],
 'Doubt': ['Doubt'],
 'Dramatic Entrance': ['Dramatic_Entrance'],
 'DramaticEntrance': ['Dramatic_Entrance'],
 'Dropkick': ['Dropkick'],
 'Dual Wield': ['Dual_Wield'],
 'DualWield': ['Dual_Wield'],
 'Dualcast': ['Dualcast'],
 'Echo Form': ['Echo_Form'],
 'EchoForm': ['Echo_Form'],
 'Electrodynamics': ['Electrodynamics'],
 'Empty Body': ['Empty_Body'],
 'Empty Fist': ['Empty_Fist'],
 'Empty Mind': ['Empty_Mind'],
 'EmptyBody': ['Empty_Body'],
 'EmptyFist': ['Empty_Fist'],
 'EmptyMind': ['Empty_Mind'],
 'Endless Agony': ['Endless_Agony'],
 'EndlessAgony': ['Endless_Agony'],
 'Enlightenment': ['Enlightenment'],
 'Entrench': ['Entrench'],
 'Envenom': ['Envenom'],
 'Equilibrium': ['Equilibrium'],
 'Eruption': ['Eruption'],
 'Escape Plan': ['Escape_Plan'],
 'Establishment': ['Establishment'],
 'Evaluate': ['Evaluate'],
 'Eviscerate': ['Eviscerate'],
 'Evolve': ['Evolve'],
 'Exhume': ['Exhume'],
 'Expertise': ['Expertise'],
 'Expunger': ['Expunger'],
 'FTL': ['FTL'],
 'Faster Than Light': ['FTL'],
 'FasterThanLight': ['FTL'],
 'Fasting': ['Fasting'],
 'Fear No Evil': ['Fear_No_Evil'],
 'FearNoEvil': ['Fear_No_Evil'],
 'Feed': ['Feed'],
 'Feel No Pain': ['Feel_No_Pain'],
 'FeelNoPain': ['Feel_No_Pain'],
 'Fiend Fire': ['Fiend_Fire'],
 'FiendFire': ['Fiend_Fire'],
 'Finesse': ['Finesse'],
 'Finisher': ['Finisher'],
 'Fire Breathing': ['Fire_Breathing'],
 'FireBreathing': ['Fire_Breathing'],
 'Fission': ['Fission'],
 'Flame Barrier': ['Flame_Barrier'],
 'FlameBarrier': ['Flame_Barrier'],
 'Flash of Steel': ['Flash_of_Steel'],
 'FlashofSteel': ['Flash_of_Steel'],
 'Flechettes': ['Flechettes'],
 'Flex': ['Flex'],
 'Flurry of Blows': ['Flurry_of_Blows'],
 'FlurryofBlows': ['Flurry_of_Blows'],
 'Flying Knee': ['Flying_Knee'],
 'Flying Sleeves': ['Flying_Sleeves'],
 'FlyingKnee': ['Flying_Knee'],
 'FlyingSleeves': ['Flying_Sleeves'],
 'Follow-Up': ['Follow-Up'],
 'FollowUp': ['Follow-Up'],
 'Footwork': ['Footwork'],
 'Force Field': ['Force_Field'],
 'ForceField': ['Force_Field'],
 'Foreign Influence': ['Foreign_Influence'],
 'ForeignInfluence': ['Foreign_Influence'],
 'Foresight': ['Foresight', 'Foresight'],
 'Forethought': ['Forethought', 'Forethought'],
 'Fusion': ['Fusion'],
 'Genetic Algorithm': ['Genetic_Algorithm'],
 'GeneticAlgorithm': ['Genetic_Algorithm'],
 'Ghostly Armor': ['Ghostly_Armor'],
 'GhostlyArmor': ['Ghostly_Armor'],
 'Glacier': ['Glacier'],
 'Glass Knife': ['Glass_Knife'],
 'GlassKnife': ['Glass_Knife'],
 'Go for the Eye': ['Go_for_the_Eye'],
 'GofortheEye': ['Go_for_the_Eye'],
 'Good Instincts': ['Good_Instincts'],
 'GoodInstincts': ['Good_Instincts'],
 'Grand Finale': ['Grand_Finale'],
 'GrandFinale': ['Grand_Finale'],
 'Halt': ['Halt'],
 'Hand of Greed': ['Hand_of_Greed'],
 'HandofGreed': ['Hand_of_Greed'],
 'Havoc': ['Havoc'],
 'Headbutt': ['Headbutt'],
 'Heatsinks': ['Heatsinks'],
 'Heavy Blade': ['Heavy_Blade'],
 'HeavyBlade': ['Heavy_Blade'],
 'Heel Hook': ['Heel_Hook'],
 'HeelHook': ['Heel_Hook'],
 'Hello World': ['Hello_World'],
 'Hello, World': ['Hello_World'],
 'HelloWorld': ['Hello_World'],
 'Hemokinesis': ['Hemokinesis'],
 'Hologram': ['Hologram'],
 'Hyperbeam': ['Hyperbeam'],
 'Immolate': ['Immolate'],
 'Impatience': ['Impatience'],
 'Impervious': ['Impervious'],
 'Indignation': ['Indignation'],
 'Infernal Blade': ['Infernal_Blade'],
 'InfernalBlade': ['Infernal_Blade'],
 'Infinite Blades': ['Infinite_Blades'],
 'InfiniteBlades': ['Infinite_Blades'],
 'Inflame': ['Inflame'],
 'Injury': ['Injury'],
 'Inner Peace': ['Inner_Peace'],
 'InnerPeace': ['Inner_Peace'],
 'Insight': ['Insight'],
 'Intimidate': ['Intimidate'],
 'Iron Wave': ['Iron_Wave'],
 'IronWave': ['Iron_Wave'],
 'J.A.X.': ['J.A.X.'],
 'JAX': ['J.A.X.'],
 'Jack of All Trades': ['Jack_of_All_Trades'],
 'JackofAllTrades': ['Jack_of_All_Trades'],
 'Judgment': ['Judgment'],
 'Juggernaut': ['Juggernaut'],
 'Just Lucky': ['Just_Lucky'],
 'JustLucky': ['Just_Lucky'],
 'Leap': ['Leap'],
 'Leg Sweep': ['Leg_Sweep'],
 'LegSweep': ['Leg_Sweep'],
 'Lesson Learned': ['Lesson_Learned'],
 'LessonLearned': ['Lesson_Learned'],
 'Like Water': ['Like_Water'],
 'LikeWater': ['Like_Water'],
 'Limit Break': ['Limit_Break'],
 'LimitBreak': ['Limit_Break'],
 'Loop': ['Loop'],
 'Machine Learning': ['Machine_Learning'],
 'MachineLearning': ['Machine_Learning'],
 'Madness': ['Madness'],
 'Magnetism': ['Magnetism'],
 'Malaise': ['Malaise'],
 'Master Reality': ['Master_Reality'],
 'Master of Strategy': ['Master_of_Strategy'],
 'MasterReality': ['Master_Reality'],
 'Masterful Stab': ['Masterful_Stab'],
 'MasterfulStab': ['Masterful_Stab'],
 'MasterofStrategy': ['Master_of_Strategy'],
 'Mayhem': ['Mayhem'],
 'Meditate': ['Meditate'],
 'Melter': ['Melter'],
 'Mental Fortress': ['Mental_Fortress'],
 'MentalFortress': ['Mental_Fortress'],
 'Metallicize': ['Metallicize'],
 'Metamorphosis': ['Metamorphosis'],
 'Meteor Strike': ['Meteor_Strike'],
 'MeteorStrike': ['Meteor_Strike'],
 'Mind Blast': ['Mind_Blast'],
 'MindBlast': ['Mind_Blast'],
 'Miracle': ['Miracle'],
 'Multi-Cast': ['Multi-Cast'],
 'MultiCast': ['Multi-Cast'],
 'Necronomicurse': ['Necronomicurse'],
 'Neutralize': ['Neutralize'],
 'Nightmare': ['Nightmare'],
 'Nirvana': ['Nirvana'],
 'Normality': ['Normality'],
 'Noxious Fumes': ['Noxious_Fumes'],
 'NoxiousFumes': ['Noxious_Fumes'],
 'Offering': ['Offering'],
 'Omega': ['Omega'],
 'Omniscience': ['Omniscience'],
 'Outmaneuver': ['Outmaneuver'],
 'Overclock': ['Overclock'],
 'Pain': ['Pain'],
 'Panacea': ['Panacea'],
 'Panache': ['Panache'],
 'Panic Button': ['Panic_Button'],
 'PanicButton': ['Panic_Button'],
 'Parasite': ['Parasite'],
 'Perfected Strike': ['Perfected_Strike'],
 'PerfectedStrike': ['Perfected_Strike'],
 'Perseverance': ['Perseverance'],
 'Phantasmal Killer': ['Phantasmal_Killer'],
 'PhantasmalKiller': ['Phantasmal_Killer'],
 'Piercing Wail': ['Piercing_Wail'],
 'PiercingWail': ['Piercing_Wail'],
 'Poisoned Stab': ['Poisoned_Stab'],
 'PoisonedStab': ['Poisoned_Stab'],
 'Pommel Strike': ['Pommel_Strike'],
 'PommelStrike': ['Pommel_Strike'],
 'Power Through': ['Power_Through'],
 'PowerThrough': ['Power_Through'],
 'Pray': ['Pray'],
 'Predator': ['Predator'],
 'Prepared': ['Prepared'],
 'Pressure Points': ['Pressure_Points'],
 'Pride': ['Pride'],
 'Prostrate': ['Prostrate'],
 'Protect': ['Protect'],
 'Pummel': ['Pummel'],
 'Purity': ['Purity'],
 'Quick Slash': ['Quick_Slash'],
 'QuickSlash': ['Quick_Slash'],
 'Rage': ['Rage'],
 'Ragnarok': ['Ragnarok'],
 'Rainbow': ['Rainbow'],
 'Rampage': ['Rampage'],
 'Reach Heaven': ['Reach_Heaven'],
 'ReachHeaven': ['Reach_Heaven'],
 'Reaper': ['Reaper'],
 'Reboot': ['Reboot'],
 'Rebound': ['Rebound'],
 'Reckless Charge': ['Reckless_Charge'],
 'RecklessCharge': ['Reckless_Charge'],
 'Recursion': ['Recursion'],
 'Recycle': ['Recycle'],
 'Reflex': ['Reflex'],
 'Regret': ['Regret'],
 'Reinforced Body': ['Reinforced_Body'],
 'Reprogram': ['Reprogram'],
 'Riddle with Holes': ['Riddle_with_Holes'],
 'Rip and Tear': ['Rip_and_Tear'],
 'RipandTear': ['Rip_and_Tear'],
 'Ritual Dagger': ['Ritual_Dagger'],
 'RitualDagger': ['Ritual_Dagger'],
 'Rupture': ['Rupture'],
 'Rushdown': ['Rushdown'],
 'Sadistic Nature': ['Sadistic_Nature'],
 'SadisticNature': ['Sadistic_Nature'],
 'Safety': ['Safety'],
 'Sanctity': ['Sanctity'],
 'Sands of Time': ['Sands_of_Time'],
 'SandsofTime': ['Sands_of_Time'],
 'Sash Whip': ['Sash_Whip'],
 'SashWhip': ['Sash_Whip'],
 'Scrape': ['Scrape'],
 'Scrawl': ['Scrawl'],
 'Searing Blow': ['Searing_Blow'],
 'SearingBlow': ['Searing_Blow'],
 'Second Wind': ['Second_Wind'],
 'SecondWind': ['Second_Wind'],
 'Secret Technique': ['Secret_Technique'],
 'Secret Weapon': ['Secret_Weapon'],
 'SecretTechnique': ['Secret_Technique'],
 'SecretWeapon': ['Secret_Weapon'],
 'Seeing Red': ['Seeing_Red'],
 'SeeingRed': ['Seeing_Red'],
 'Seek': ['Seek'],
 'Self Repair': ['Self_Repair'],
 'SelfRepair': ['Self_Repair'],
 'Sentinel': ['Sentinel'],
 'Setup': ['Setup'],
 'Sever Soul': ['Sever_Soul'],
 'SeverSoul': ['Sever_Soul'],
 'Shame': ['Shame'],
 'Shiv': ['Shiv'],
 'Shockwave': ['Shockwave'],
 'Shrug It Off': ['Shrug_It_Off'],
 'ShrugItOff': ['Shrug_It_Off'],
 'Signature Move': ['Signature_Move'],
 'SignatureMove': ['Signature_Move'],
 'Simmering Fury': ['Simmering_Fury'],
 'SimmeringFury': ['Simmering_Fury'],
 'Skewer': ['Skewer'],
 'Skim': ['Skim'],
 'Slice': ['Slice'],
 'Slimed': ['Slimed'],
 'Smite': ['Smite'],
 'Sneaky Strike': ['Sneaky_Strike'],
 'SneakyStrike': ['Sneaky_Strike'],
 'Spirit Shield': ['Spirit_Shield'],
 'SpiritShield': ['Spirit_Shield'],
 'Spot Weakness': ['Spot_Weakness'],
 'SpotWeakness': ['Spot_Weakness'],
 'Stack': ['Stack'],
 'Static Discharge': ['Static_Discharge'],
 'StaticDischarge': ['Static_Discharge'],
 'Steam Barrier': ['Steam_Barrier'],
 'SteamBarrier': ['Steam_Barrier'],
 'Storm': ['Storm'],
 'Storm of Steel': ['Storm_of_Steel'],
 'StormofSteel': ['Storm_of_Steel'],
 'Streamline': ['Streamline'],
 'Strike': ['Strike_(Defect)', 'Strike_(Ironclad)', 'Strike_(Silent)', 'Strike_(Watcher)'],
 'Strike (Defect)': ['Strike_(Defect)'],
 'Strike (Ironclad)': ['Strike_(Ironclad)'],
 'Strike (Silent)': ['Strike_(Silent)'],
 'Strike (Watcher)': ['Strike_(Watcher)'],
 'Study': ['Study'],
 'Sucker Punch': ['Sucker_Punch'],
 'SuckerPunch': ['Sucker_Punch'],
 'Sunder': ['Sunder'],
 'Survivor': ['Survivor'],
 'Sweeping Beam': ['Sweeping_Beam'],
 'SweepingBeam': ['Sweeping_Beam'],
 'Swift Strike': ['Swift_Strike'],
 'SwiftStrike': ['Swift_Strike'],
 'Swivel': ['Swivel'],
 'Sword Boomerang': ['Sword_Boomerang'],
 'SwordBoomerang': ['Sword_Boomerang'],
 'TURBO': ['TURBO'],
 'Tactician': ['Tactician'],
 'Talk to the Hand': ['Talk_to_the_Hand'],
 'TalktotheHand': ['Talk_to_the_Hand'],
 'Tantrum': ['Tantrum'],
 'Tempest': ['Tempest'],
 'Terror': ['Terror'],
 'The Bomb': ['The_Bomb'],
 'Thinking Ahead': ['Thinking_Ahead'],
 'ThinkingAhead': ['Thinking_Ahead'],
 'Third Eye': ['Third_Eye'],
 'ThirdEye': ['Third_Eye'],
 'Through Violence': ['Through_Violence'],
 'ThroughViolence': ['Through_Violence'],
 'Thunder Strike': ['Thunder_Strike'],
 'ThunderStrike': ['Thunder_Strike'],
 'Thunderclap': ['Thunderclap'],
 'Tools of the Trade': ['Tools_of_the_Trade'],
 'ToolsoftheTrade': ['Tools_of_the_Trade'],
 'Tranquility': ['Tranquility'],
 'Transmutation': ['Transmutation'],
 'Trip': ['Trip'],
 'True Grit': ['True_Grit'],
 'TrueGrit': ['True_Grit'],
 'Twin Strike': ['Twin_Strike'],
 'TwinStrike': ['Twin_Strike'],
 'Unload': ['Unload'],
 'Uppercut': ['Uppercut'],
 'Vault': ['Vault'],
 'Vigilance': ['Vigilance'],
 'Violence': ['Violence'],
 'Void': ['Void'],
 'Wallop': ['Wallop'],
 'Warcry': ['Warcry'],
 'Wave of the Hand': ['Wave_of_the_Hand'],
 'WaveoftheHand': ['Wave_of_the_Hand'],
 'Weave': ['Weave'],
 'Well-Laid Plans': ['Well-Laid_Plans'],
 'WellLaidPlans': ['Well-Laid_Plans'],
 'Wheel Kick': ['Wheel_Kick'],
 'WheelKick': ['Wheel_Kick'],
 'Whirlwind': ['Whirlwind'],
 'White Noise': ['White_Noise'],
 'WhiteNoise': ['White_Noise'],
 'Wild Strike': ['Wild_Strike'],
 'WildStrike': ['Wild_Strike'],
 'Windmill Strike': ['Windmill_Strike'],
 'WindmillStrike': ['Windmill_Strike'],
 'Wish': ['Wish'],
 'Worship': ['Worship'],
 'Wound': ['Wound'],
 'Wraith Form': ['Wraith_Form'],
 'WraithForm': ['Wraith_Form'],
 'Wreath of Flame': ['Wreath_of_Flame'],
 'WreathofFlame': ['Wreath_of_Flame'],
 'Writhe': ['Writhe'],
 'Zap': ['Zap'],
 'bonk': ['Wallop'],
 'orz': ['Prostrate'],
 'Ω': ['Omega'],
 'α': ['Alpha'],
 'β': ['Beta'],
 '⏳': ['Sands_of_Time'],
 '☀️': ['Miracle'],
 '♠️': ['Calculated_Gamble'],
 '♥️': ['Finesse'],
 '♻️': ['Recycle'],
 '♾️': ['Loop'],
 '⚔️': ['Clash'],
 '⚖️': ['Neutralize'],
 '⚙️': ['Core_Surge'],
 '⚡': ['Thunderclap', 'Zap'],
 '⛓️': ['Dark_Shackles', 'Normality'],
 '✂️': ['Cut_Through_Fate'],
 '✊': ['Empty_Fist', 'Survivor', 'Uppercut'],
 '✋': ['Talk_to_the_Hand'],
 '✍️': ['Scrawl', 'Well-Laid_Plans'],
 '❓': ['Biased_Cognition'],
 '一笑了之': ['Shrug_It_Off'],
 '万物': ['All_for_One'],
 '万物一心': ['All_for_One'],
 '万能药': ['Panacea'],
 '上勾拳': ['Uppercut'],
 '下注': ['Calculated_Gamble'],
 '不惧妖邪': ['Fear_No_Evil'],
 '不现实': ['Carve_Reality', 'Deceive_Reality', 'Master_Reality'],
 '不让': ['Halt'],
 '专长': ['Expertise'],
 '中和': ['Neutralize'],
 '中立': ['Neutralize'],
 '串刺': ['Skewer'],
 '串烧': ['Skewer'],
 '义愤': ['Indignation'],
 '义愤填膺': ['Indignation'],
 '乱战': ['Mayhem'],
 '乾坤一掷': ['Unload'],
 '二重身': ['Doppelganger'],
 '五体': ['Prostrate'],
 '五体投地': ['Prostrate'],
 '交锋': ['Clash'],
 '亮剑': ['Flash_of_Steel'],
 '人工制品': ['Core_Surge'],
 '人工智能': ['Creative_AI'],
 '他山': ['Foreign_Influence'],
 '他山之石': ['Foreign_Influence'],
 '以手': ['Talk_to_the_Hand'],
 '以手拒之': ['Talk_to_the_Hand'],
 '以暴制暴': ['Through_Violence'],
 '以牙还牙': ['Blood_for_Blood'],
 '以血': ['Blood_for_Blood'],
 '以血还血': ['Blood_for_Blood'],
 '仪式匕首': ['Ritual_Dagger'],
 '优秀直觉': ['Good_Instincts'],
 '伤口': ['Wound'],
 '余像': ['After_Image'],
 '你好': ['Hello_World'],
 '你好，世界': ['Hello_World'],
 '供奉': ['Consecrate'],
 '侥幸': ['Just_Lucky'],
 '保龄球': ['Bowling_Bash'],
 '修车': ['Self_Repair'],
 '偏差认知': ['Biased_Cognition'],
 '偏折': ['Deflect'],
 '停顿': ['Halt'],
 '偷袭': ['Sneaky_Strike'],
 '催化': ['Catalyst'],
 '催化剂': ['Catalyst'],
 '傲慢': ['Pride'],
 '充电': ['Charge_Battery'],
 '先机': ['Outmaneuver'],
 '先见': ['Foresight'],
 '先见之明': ['Foresight'],
 '光剑': ['Expunger'],
 '光束': ['Beam_Cell', 'Hyperbeam', 'Mind_Blast', 'Sweeping_Beam'],
 '光束射线': ['Beam_Cell'],
 '光辉': ['Brilliance'],
 '光速': ['FTL'],
 '入场': ['Dramatic_Entrance'],
 '全力': ['All-Out_Attack'],
 '全力攻击': ['All-Out_Attack'],
 '全息': ['Hologram'],
 '全息影像': ['Hologram'],
 '全知': ['Omniscience'],
 '全神': ['Concentrate'],
 '全神贯注': ['Concentrate'],
 '全身撞击': ['Body_Slam'],
 '关节': ['Crush_Joints'],
 '内切': ['Eviscerate'],
 '内宁': ['Inner_Peace'],
 '内心宁静': ['Inner_Peace'],
 '内核': ['TURBO'],
 '内核加速': ['TURBO'],
 '内脏切除': ['Eviscerate'],
 '冥想': ['Meditate'],
 '冰寒': ['Chill'],
 '冰川': ['Glacier'],
 '冰球': ['Chill', 'Cold_Snap', 'Coolheaded', 'Glacier', 'Rainbow'],
 '冲刺': ['Dash'],
 '决斗': ['Clash'],
 '冷头': ['Coolheaded'],
 '冷静头脑': ['Coolheaded'],
 '净化': ['Purity'],
 '凌迟': ['A_Thousand_Cuts'],
 '凡庸': ['Normality'],
 '刀刃之舞': ['Blade_Dance'],
 '刀尖': ['Sadistic_Nature'],
 '刀舞': ['Blade_Dance'],
 '分离': ['Sunder'],
 '分身': ['Doppelganger'],
 '切割': ['Slice'],
 '创造性AI': ['Creative_AI'],
 '刮削': ['Scrape'],
 '刺穿': ['Expunger'],
 '刺耳': ['Piercing_Wail'],
 '剑柄': ['Pommel_Strike'],
 '剑柄打击': ['Pommel_Strike'],
 '剪刀': ['Cut_Through_Fate'],
 '劈': ['Cleave', 'Heavy_Blade', 'Slice'],
 '力场': ['Force_Field'],
 '加倍': ['Double_Energy'],
 '加速': ['Overclock'],
 '势不可当': ['Juggernaut'],
 '势不可挡': ['Juggernaut'],
 '勒脖': ['Choke'],
 '勤学': ['Lesson_Learned'],
 '勤学精进': ['Lesson_Learned'],
 '包扎': ['Bandage_Up'],
 '匕首': ['Cloak_and_Dagger', 'Dagger_Spray', 'Dagger_Throw', 'Ritual_Dagger', 'Shiv', 'Storm_of_Steel'],
 '匕首雨': ['Dagger_Spray'],
 '化体': ['Empty_Body'],
 '化体为空': ['Empty_Body'],
 '化拳': ['Empty_Fist'],
 '化拳为空': ['Empty_Fist'],
 '化智': ['Empty_Mind'],
 '化智为空': ['Empty_Mind'],
 '千刀万剐': ['A_Thousand_Cuts'],
 '千疮百孔': ['Riddle_with_Holes'],
 '千穿百刺': ['Riddle_with_Holes'],
 '升天': ['Reach_Heaven'],
 '华丽': ['Grand_Finale'],
 '华丽收场': ['Grand_Finale'],
 '卡车': ['Juggernaut'],
 '印章': ['Establishment'],
 '卸载': ['Unload'],
 '双倍能量': ['Double_Energy'],
 '双击': ['Double_Tap'],
 '双刀': ['Dual_Wield'],
 '双发': ['Double_Tap'],
 '双打': ['Twin_Strike'],
 '双持': ['Dual_Wield'],
 '双放': ['Dualcast'],
 '双重存在': ['Doppelganger'],
 '双重打击': ['Twin_Strike'],
 '双重释放': ['Dualcast'],
 '反射': ['Reflex'],
 '反弹': ['Rebound'],
 '发掘': ['Exhume'],
 '发泄': ['Tantrum'],
 '发现': ['Discovery'],
 '受伤': ['Injury'],
 '史莱姆': ['Evolve', 'Intimidate', 'Nightmare', 'Slimed'],
 '叶子': ['Inner_Peace'],
 '后悔': ['Regret'],
 '后空翻': ['Backflip'],
 '吐火': ['Fire_Breathing'],
 '启动流程': ['Boot_Sequence'],
 '吸血': ['Bite'],
 '吸铁石': ['Magnetism'],
 '吼': ['Rage', 'Warcry'],
 '告示': ['Evaluate'],
 '呐喊': ['Madness'],
 '呼吸': ['Deep_Breath'],
 '哨兵': ['Sentinel'],
 '哨卫': ['Sentinel'],
 '喷火': ['Fire_Breathing'],
 '噩梦': ['Nightmare'],
 '噬咬': ['Bite'],
 '回响': ['Echo_Form'],
 '回响形态': ['Echo_Form'],
 '回收': ['Recycle'],
 '回旋镖': ['Sword_Boomerang'],
 '回环踢': ['Wheel_Kick'],
 '回血': ['Bandage_Up'],
 '国象': ['Master_of_Strategy'],
 '图书馆': ['Omniscience'],
 '圣洁': ['Sanctity'],
 '地狱之刃': ['Infernal_Blade'],
 '均衡': ['Equilibrium'],
 '坚不可摧': ['Impervious'],
 '坚毅': ['True_Grit'],
 '坚韧': ['Perseverance'],
 '堆叠': ['Stack'],
 '堆栈': ['Stack'],
 '增幅': ['Amplify'],
 '壁垒': ['Barricade'],
 '声东击西': ['Distraction'],
 '多播': ['Multi-Cast'],
 '多放': ['Multi-Cast'],
 '多重释放': ['Multi-Cast'],
 '夜魇': ['Nightmare'],
 '大刀': ['Forethought', 'Heavy_Blade'],
 '大手': ['Fear_No_Evil'],
 '大脑升级': ['Empty_Mind', 'Enlightenment'],
 '天人': ['Deva_Form'],
 '天人形态': ['Deva_Form'],
 '天使': ['Apotheosis'],
 '天平': ['Neutralize'],
 '天眼': ['Third_Eye'],
 '头槌': ['Headbutt'],
 '奇迹': ['Miracle'],
 '奖杯': ['Pride'],
 '如水': ['Like_Water'],
 '妖邪': ['Fear_No_Evil'],
 '妙计': ['Finesse'],
 '威吓': ['Intimidate'],
 '子弹时间': ['Bullet_Time'],
 '学习': ['Lesson_Learned', 'Study'],
 '安全': ['Safety'],
 '安宁': ['Tranquility'],
 '完美打击': ['Perfected_Strike'],
 '审判': ['Judgment'],
 '寄托': ['Well-Laid_Plans'],
 '寄生': ['Parasite'],
 '寒流': ['Cold_Snap'],
 '寻找': ['Seek'],
 '射线': ['Beam_Cell', 'Hyperbeam', 'Mind_Blast', 'Sweeping_Beam'],
 '小刀': ['Shiv'],
 '小毒': ['Deadly_Poison'],
 '小电': ['Zap'],
 '小金人': ['Impervious'],
 '尖啸': ['Piercing_Wail'],
 '尸爆': ['Corpse_Explosion'],
 '尸爆术': ['Corpse_Explosion'],
 '岿然不动': ['Impervious'],
 '巩固': ['Entrench'],
 '带毒刺击': ['Poisoned_Stab'],
 '平安': ['Safety'],
 '幸存': ['Survivor'],
 '幸运一击': ['Just_Lucky'],
 '幻影杀手': ['Phantasmal_Killer'],
 '幻杀': ['Phantasmal_Killer'],
 '幽灵铠甲': ['Ghostly_Armor'],
 '幽魂形态': ['Wraith_Form'],
 '开悟': ['Enlightenment'],
 '开机': ['Boot_Sequence'],
 '开溜': ['Escape_Plan'],
 '开膛破肚': ['Eviscerate'],
 '张贴': ['Evaluate'],
 '弹回': ['Rebound'],
 '弹幕齐射': ['Barrage'],
 '弹跳药瓶': ['Bouncing_Flask'],
 '强化剂': ['J.A.X.'],
 '当头': ['Wallop'],
 '当头棒喝': ['Wallop'],
 '形态': ['Demon_Form', 'Deva_Form', 'Echo_Form', 'Wraith_Form'],
 '彩球': ['Fusion', 'Meteor_Strike'],
 '彩虹': ['Rainbow'],
 '御血术': ['Hemokinesis'],
 '循环': ['Loop'],
 '心堡': ['Mental_Fortress'],
 '心灵堡垒': ['Mental_Fortress'],
 '心灵震慑': ['Mind_Blast'],
 '必备工具': ['Tools_of_the_Trade'],
 '快斩': ['Quick_Slash'],
 '快检': ['Skim'],
 '快速检索': ['Skim'],
 '怀疑': ['Doubt'],
 '怒火中烧': ['Simmering_Fury'],
 '思考': ['Concentrate'],
 '急躁': ['Impatience'],
 '恐吓': ['Intimidate'],
 '恐怖': ['Terror'],
 '恶魔': ['Demon_Form', 'Fiend_Fire'],
 '恶魔之焰': ['Fiend_Fire'],
 '恶魔形态': ['Demon_Form'],
 '悔恨': ['Regret'],
 '悟': ['Enlightenment'],
 '惩恶': ['Smite'],
 '想吃': ['Feed'],
 '愁云': ['Doom_and_Gloom'],
 '愁云惨淡': ['Doom_and_Gloom'],
 '愤怒': ['Anger'],
 '战专': ['Battle_Trance'],
 '战吼': ['Warcry'],
 '战士': ['Bash', 'Defend_(Ironclad)', 'Strike_(Ironclad)'],
 '战斗专注': ['Battle_Trance'],
 '战术大师': ['Tactician'],
 '战歌': ['Battle_Hymn'],
 '战略大师': ['Master_of_Strategy'],
 '手铐': ['Normality'],
 '扑克': ['Calculated_Gamble'],
 '打光': ['Terror'],
 '打击': ['Meteor_Strike',
        'Perfected_Strike',
        'Pommel_Strike',
        'Strike_(Defect)',
        'Strike_(Ironclad)',
        'Strike_(Silent)',
        'Strike_(Watcher)',
        'Swift_Strike',
        'Thunder_Strike',
        'Twin_Strike',
        'Wild_Strike',
        'Windmill_Strike'],
 '打钱': ['Hand_of_Greed'],
 '扩容': ['Capacitor'],
 '扫腿': ['Leg_Sweep'],
 '扫荡射线': ['Sweeping_Beam'],
 '扳手': ['Self_Repair'],
 '投匕': ['Dagger_Throw'],
 '投掷匕首': ['Dagger_Throw'],
 '投降': ['Disarm'],
 '抢占': ['Outmaneuver'],
 '抢占先机': ['Outmaneuver'],
 '护盾': ['Auto-Shields', 'Force_Field', 'Spirit_Shield'],
 '护身': ['Protect'],
 '抽牌': ['Acrobatics',
        'Adrenaline',
        'Backflip',
        'Battle_Trance',
        'Burning_Pact',
        'Compile_Driver',
        'Dark_Embrace',
        'Empty_Mind',
        'Evolve',
        'Expertise',
        'Fission',
        'Flash_of_Steel',
        'Impatience',
        'Inner_Peace',
        'Insight',
        'Master_of_Strategy',
        'Offering',
        'Overclock',
        'Pommel_Strike',
        'Reboot',
        'Rushdown',
        'Scrape',
        'Scrawl',
        'Secret_Technique',
        'Secret_Weapon',
        'Shrug_It_Off',
        'Simmering_Fury',
        'Skim',
        'Wheel_Kick'],
 '招牌技': ['Signature_Move'],
 '拳': ['Pummel'],
 '拼图': ['Insight'],
 '按钮': ['Panic_Button'],
 '挥手': ['Wave_of_the_Hand'],
 '捕兽夹': ['Setup'],
 '捕食': ['Predator'],
 '掏心': ['Brutality'],
 '推石头': ['Perseverance'],
 '握手': ['Burning_Pact'],
 '搜寻': ['Seek'],
 '摆手': ['Wave_of_the_Hand'],
 '撑杆': ['Vault'],
 '撕裂': ['Rupture'],
 '操控现实': ['Master_Reality'],
 '操纵现实': ['Master_Reality'],
 '收集': ['Collect'],
 '改良': ['Streamline'],
 '改造现实': ['Carve_Reality'],
 '攻防一体': ['Dash', 'Iron_Wave'],
 '放血': ['Bloodletting'],
 '敏捷': ['Footwork'],
 '教训': ['Lesson_Learned'],
 '散热': ['Heatsinks'],
 '散热片': ['Heatsinks'],
 '敬拜': ['Worship'],
 '斋': ['Fasting'],
 '斋戒': ['Fasting'],
 '斗匕': ['Cloak_and_Dagger'],
 '斗篷与匕首': ['Cloak_and_Dagger'],
 '斩': ['Cleave', 'Glass_Knife', 'Quick_Slash', 'Rampage', 'Sever_Soul', 'Slice', 'Whirlwind'],
 '斩破命运': ['Cut_Through_Fate'],
 '断魂': ['Sever_Soul'],
 '断魂斩': ['Sever_Soul'],
 '斯安威斯坦': ['After_Image'],
 '旋身': ['Swivel'],
 '旋转打击': ['Windmill_Strike'],
 '旋风斩': ['Whirlwind'],
 '无实体': ['Apparition'],
 '无尽痛苦': ['Endless_Agony'],
 '无尽苦痛': ['Endless_Agony'],
 '无惧': ['Feel_No_Pain'],
 '无惧疼痛': ['Feel_No_Pain'],
 '无穷': ['Loop'],
 '无谋': ['Reckless_Charge'],
 '无谋冲锋': ['Reckless_Charge'],
 '无限刀刃': ['Infinite_Blades'],
 '早有准备': ['Prepared'],
 '时之沙': ['Sands_of_Time'],
 '晕眩': ['Dazed'],
 '智力': ['Empty_Mind'],
 '暴力': ['Violence'],
 '暴怒': ['Eruption'],
 '暴走': ['Rampage'],
 '暴雪': ['Blizzard'],
 '暴风雨': ['Tempest'],
 '暴风雪': ['Blizzard'],
 '替身': ['Doppelganger'],
 '有罪': ['Judgment'],
 '未雨绸缪': ['Thinking_Ahead'],
 '本能': ['Reflex'],
 '本能反应': ['Reflex'],
 '机器人': ['Defend_(Defect)', 'Dualcast', 'Strike_(Defect)', 'Zap'],
 '机器学习': ['Machine_Learning'],
 '机宝': ['Defend_(Defect)', 'Dualcast', 'Strike_(Defect)', 'Zap'],
 '机械降神': ['Deus_Ex_Machina'],
 '杂技': ['Acrobatics'],
 '核心电泳': ['Core_Surge'],
 '梦魇': ['Nightmare'],
 '检索': ['Skim'],
 '模糊': ['Blur'],
 '横扫': ['Cleave'],
 '欧米伽': ['Omega'],
 '欺瞒': ['Deceive_Reality'],
 '欺瞒现实': ['Deceive_Reality'],
 '武装': ['Armaments'],
 '歪嘴': ['Good_Instincts'],
 '死亡收割': ['Reaper'],
 '死割': ['Reaper'],
 '死吧': ['Die_Die_Die'],
 '死吧死吧死吧': ['Die_Die_Die'],
 '死灵诅咒': ['Necronomicurse'],
 '残影': ['Blur'],
 '残暴': ['Brutality'],
 '残杀': ['Carnage'],
 '残虐天性': ['Sadistic_Nature'],
 '毒云': ['Crippling_Cloud'],
 '毒刺': ['Poisoned_Stab'],
 '毒气': ['Noxious_Fumes'],
 '毒瓶': ['Bouncing_Flask'],
 '毒药': ['Deadly_Poison'],
 '毒雾': ['Noxious_Fumes'],
 '汇聚': ['Aggregate'],
 '汇集': ['Aggregate'],
 '注意力': ['Distraction'],
 '洞察': ['Insight'],
 '洞见': ['Insight'],
 '活动肌肉': ['Flex'],
 '流云': ['Flying_Sleeves'],
 '流云飞袖': ['Flying_Sleeves'],
 '流星锤': ['Bash'],
 '涂毒': ['Envenom'],
 '涅槃': ['Nirvana'],
 '消逝': ['Decay'],
 '涡轮': ['TURBO'],
 '润': ['Escape_Plan', 'TURBO'],
 '淬毒': ['Envenom'],
 '深呼吸': ['Deep_Breath'],
 '深谋远虑': ['Thinking_Ahead'],
 '混沌': ['Chaos'],
 '渎神': ['Blasphemy'],
 '渐强': ['Crescendo'],
 '滑倒': ['Clumsy', 'Trip'],
 '漆黑': ['Darkness'],
 '潦草': ['Scrawl'],
 '潦草急就': ['Scrawl'],
 '火吐': ['Fire_Breathing'],
 '火屏': ['Flame_Barrier'],
 '火漆': ['Establishment'],
 '火焰吐息': ['Fire_Breathing'],
 '火焰屏障': ['Flame_Barrier'],
 '火焰纹': ['Wreath_of_Flame'],
 '灭除之刃': ['Expunger'],
 '灵体': ['Apparition'],
 '灵动': ['Footwork'],
 '灵动步法': ['Footwork'],
 '灵视': ['Foresight'],
 '灼': ['Searing_Blow'],
 '灼伤': ['Burn'],
 '灼热攻击': ['Searing_Blow'],
 '灾祸': ['Bane'],
 '炸弹': ['The_Bomb'],
 '点穴': ['Pressure_Points'],
 '炼制药水': ['Alchemize'],
 '炼药': ['Alchemize'],
 '炼金': ['Alchemize'],
 '烤串': ['Skewer'],
 '烧牌': ['Burning_Pact', 'Recycle', 'Second_Wind', 'Sever_Soul'],
 '熔化': ['Melter'],
 '燃烧': ['Inflame'],
 '燃烧契约': ['Burning_Pact'],
 '燔祭': ['Immolate'],
 '爆发': ['Burst'],
 '爆炸': ['Corpse_Explosion'],
 '爪': ['Claw', 'Rip_and_Tear', 'Scrape'],
 '爪击': ['Claw'],
 '犯病': ['All-Out_Attack'],
 '狂乱撕扯': ['Rip_and_Tear'],
 '狂宴': ['Feed'],
 '狂怒': ['Rage'],
 '狂战': ['Berserk'],
 '狂暴': ['Berserk'],
 '狂野打击': ['Wild_Strike'],
 '独门': ['Expertise'],
 '独门技术': ['Expertise'],
 '猎人': ['Defend_(Silent)', 'Neutralize', 'Strike_(Silent)', 'Survivor'],
 '猎手': ['Defend_(Silent)', 'Neutralize', 'Strike_(Silent)', 'Survivor'],
 '猎杀': ['Predator'],
 '猎杀者': ['Predator'],
 '猛虎': ['Rushdown'],
 '猛虎下山': ['Rushdown'],
 '献祭': ['Offering'],
 '玉足': ['Footwork'],
 '玻璃刀': ['Glass_Knife'],
 '玻璃刀刃': ['Glass_Knife'],
 '球状闪电': ['Ball_Lightning'],
 '球闪': ['Ball_Lightning'],
 '生存者': ['Survivor'],
 '生还': ['Survivor'],
 '电击': ['Zap'],
 '电动力': ['Electrodynamics'],
 '电动力学': ['Electrodynamics'],
 '电容': ['Capacitor'],
 '电泳': ['Core_Surge'],
 '电球': ['Ball_Lightning', 'Electrodynamics', 'Rainbow', 'Static_Discharge', 'Storm', 'Tempest', 'Zap'],
 '疑虑': ['Doubt'],
 '疯狂': ['Madness'],
 '疯狂星期四': ['Feed'],
 '疼': ['Pain'],
 '疼痛': ['Pain'],
 '疾风': ['Flurry_of_Blows'],
 '疾风连击': ['Flurry_of_Blows'],
 '痕': ['Claw'],
 '痛击': ['Bash'],
 '痛苦': ['Endless_Agony'],
 '登场': ['Dramatic_Entrance'],
 '白噪声': ['White_Noise'],
 '白玫瑰': ['Purity'],
 '盛怒': ['Seeing_Red'],
 '盯': ['Terror'],
 '直觉': ['Good_Instincts'],
 '看看': ['Spot_Weakness'],
 '眩晕': ['Dazed'],
 '眼部': ['Go_for_the_Eye'],
 '眼部攻击': ['Go_for_the_Eye'],
 '瞄准靶心': ['Bullseye'],
 '瞄靶': ['Bullseye'],
 '瞪': ['Seeing_Red'],
 '研习': ['Study'],
 '研究': ['Study'],
 '破灭': ['Havoc'],
 '硬化': ['Reinforced_Body'],
 '硬化机体': ['Reinforced_Body'],
 '硬币': ['Just_Lucky'],
 '硬撑': ['Power_Through'],
 '确立基础': ['Establishment'],
 '碎片': ['Defragment'],
 '碎片整理': ['Defragment'],
 '碰撞连击': ['Bowling_Bash'],
 '磁力': ['Magnetism'],
 '磁铁': ['Magnetism'],
 '祈祷': ['Pray'],
 '神化': ['Apotheosis'],
 '神气': ['Panache'],
 '神气制胜': ['Panache'],
 '祭品': ['Offering'],
 '祭献': ['Offering'],
 '秘密技法': ['Secret_Technique'],
 '秘密武器': ['Secret_Weapon'],
 '穴位': ['Pressure_Points'],
 '穿刺': ['Skewer'],
 '突然一拳': ['Sucker_Punch'],
 '突破极限': ['Limit_Break'],
 '立地升天': ['Reach_Heaven'],
 '笨': ['Clumsy'],
 '笨拙': ['Clumsy'],
 '第三只眼': ['Third_Eye'],
 '简化': ['Streamline'],
 '算法': ['Genetic_Algorithm'],
 '粉关': ['Crush_Joints'],
 '粉碎关节': ['Crush_Joints'],
 '粘液': ['Slimed'],
 '精准': ['Accuracy'],
 '精巧刺击': ['Masterful_Stab'],
 '精神护盾': ['Spirit_Shield'],
 '精简': ['Streamline'],
 '精简改良': ['Streamline'],
 '紧急按钮': ['Panic_Button'],
 '红眼': ['Seeing_Red'],
 '纯洁': ['Purity'],
 '终结技': ['Finisher'],
 '绊倒': ['Trip'],
 '结末': ['Conclude'],
 '结茧': ['Chrysalis'],
 '绷带': ['Bandage_Up'],
 '缓冲': ['Buffer'],
 '编冲': ['Compile_Driver'],
 '编译': ['Compile_Driver'],
 '编译冲击': ['Compile_Driver'],
 '缴械': ['Disarm'],
 '羞愧': ['Shame'],
 '羞耻': ['Shame'],
 '羽化': ['Metamorphosis'],
 '羽毛笔': ['Well-Laid_Plans'],
 '翻滚': ['Dodge_and_Roll'],
 '耗尽': ['Consume'],
 '耸肩': ['Hologram', 'Shrug_It_Off'],
 '耸肩无视': ['Shrug_It_Off'],
 '聚变': ['Fusion'],
 '聚能成刃': ['Conjure_Blade'],
 '肌肉': ['Flex'],
 '肚皮': ['Body_Slam'],
 '肾上腺素': ['Adrenaline'],
 '背刺': ['Backstab'],
 '背包': ['Prepared'],
 '腐化': ['Corruption'],
 '腐朽': ['Decay'],
 '腐败': ['Decay'],
 '腰子': ['Adrenaline'],
 '腰带': ['Sash_Whip', 'True_Grit'],
 '腰带抽打': ['Sash_Whip'],
 '腾跃': ['Vault'],
 '自动护盾': ['Auto-Shields'],
 '自我修复': ['Self_Repair'],
 '自燃': ['Combust'],
 '致命毒药': ['Deadly_Poison'],
 '致残毒云': ['Crippling_Cloud'],
 '致盲': ['Blind'],
 '芥末': ['Conclude'],
 '花样百出': ['Jack_of_All_Trades'],
 '苦恼': ['Writhe'],
 '苦痛': ['Endless_Agony'],
 '茧': ['Chrysalis'],
 '荆棘': ['Caltrops'],
 '药水': ['Panacea'],
 '萎靡': ['Malaise'],
 '蒸汽护壁': ['Steam_Barrier'],
 '虐待狂': ['Sadistic_Nature'],
 '虔信': ['Devotion'],
 '虔诚': ['Devotion'],
 '虚空': ['Void'],
 '蛋蛋': ['Dualcast'],
 '蛹': ['Chrysalis'],
 '蜡烛': ['Devotion'],
 '蝴蝶': ['Metamorphosis'],
 '血债血偿': ['Blood_for_Blood'],
 '血迹': ['Violence'],
 '裂变': ['Fission'],
 '西西弗斯': ['Perseverance'],
 '要害': ['Go_for_the_Eye'],
 '观察': ['Spot_Weakness'],
 '观察弱点': ['Spot_Weakness'],
 '观者': ['Defend_(Watcher)', 'Eruption', 'Strike_(Watcher)', 'Vigilance'],
 '警惕': ['Vigilance'],
 '计划妥当': ['Well-Laid_Plans'],
 '计妥': ['Well-Laid_Plans'],
 '计算下注': ['Calculated_Gamble'],
 '认知偏差': ['Biased_Cognition'],
 '许愿': ['Wish'],
 '设定': ['Setup'],
 '评估': ['Evaluate'],
 '诅咒': ['Curse_of_the_Bell',
        'Decay',
        'Doubt',
        'Injury',
        'Necronomicurse',
        'Normality',
        'Pain',
        'Parasite',
        'Pride',
        'Shame',
        'Writhe'],
 '诸神': ['Ragnarok'],
 '诸神之黄昏': ['Ragnarok'],
 '诸神黄昏': ['Ragnarok'],
 '谢幕': ['Grand_Finale'],
 '贝塔': ['Beta'],
 '贪婪': ['Hand_of_Greed'],
 '贪婪之手': ['Hand_of_Greed'],
 '赌博': ['Calculated_Gamble'],
 '赞美太阳': ['Worship'],
 '超能光束': ['Hyperbeam'],
 '超越光速': ['FTL'],
 '超频': ['Overclock'],
 '越界': ['Limit_Break'],
 '足跟勾': ['Heel_Hook'],
 '跑': ['TURBO'],
 '跳瓶': ['Bouncing_Flask'],
 '踢': ['Wheel_Kick'],
 '转化': ['Transmutation'],
 '迂回': ['Weave'],
 '迅捷打击': ['Swift_Strike'],
 '进化': ['Evolve'],
 '进阶之灾': ["Ascender's_Bane"],
 '连续拳': ['Pummel'],
 '追击': ['Follow-Up'],
 '逃脱': ['Escape_Plan'],
 '逃脱计划': ['Escape_Plan'],
 '逃跑': ['Escape_Plan'],
 '递归': ['Recursion'],
 '通晓': ['Omniscience'],
 '通晓万物': ['Omniscience'],
 '逮捕': ['Normality'],
 '遗传': ['Genetic_Algorithm'],
 '遗传算法': ['Genetic_Algorithm'],
 '邪魅一笑': ['Good_Instincts'],
 '部署': ['Setup'],
 '重刃': ['Heavy_Blade'],
 '重启': ['Reboot'],
 '重振': ['Second_Wind'],
 '重振精神': ['Second_Wind'],
 '重编程': ['Reprogram'],
 '重锤': ['Bludgeon'],
 '金刚臂': ['Clothesline'],
 '金属化': ['Metallicize'],
 '钢铁风暴': ['Storm_of_Steel'],
 '钢风': ['Storm_of_Steel'],
 '铁斩波': ['Iron_Wave'],
 '铁蒺藜': ['Caltrops'],
 '铃铛的诅咒': ['Curse_of_the_Bell'],
 '铠甲': ['Ghostly_Armor'],
 '镣铐': ['Dark_Shackles'],
 '闪亮登场': ['Dramatic_Entrance'],
 '闪电霹雳': ['Thunderclap'],
 '闪躲': ['Dodge_and_Roll'],
 '闪躲翻滚': ['Dodge_and_Roll'],
 '防御': ['Defend_(Defect)', 'Defend_(Ironclad)', 'Defend_(Silent)', 'Defend_(Watcher)'],
 '阿尔法': ['Alpha'],
 '附魔': ['Conjure_Blade'],
 '陨石': ['Meteor_Strike'],
 '陨石打击': ['Meteor_Strike'],
 '隐秘': ['Sneaky_Strike'],
 '隐秘打击': ['Sneaky_Strike'],
 '集中': ['Biased_Cognition', 'Consume', 'Defragment'],
 '雕刻': ['Carve_Reality'],
 '雷暴': ['Storm'],
 '雷霆': ['Thunder_Strike'],
 '雷霆打击': ['Thunder_Strike'],
 '震荡波': ['Shockwave'],
 '霹雳': ['Thunderclap'],
 '静电释放': ['Static_Discharge'],
 '靶心': ['Bullseye'],
 '顺劈斩': ['Cleave'],
 '预谋': ['Forethought'],
 '风车': ['Windmill_Strike'],
 '飞刀': ['Accuracy'],
 '飞剑回旋镖': ['Sword_Boomerang'],
 '飞膝': ['Flying_Knee'],
 '飞袖': ['Flying_Sleeves'],
 '飞跃': ['Leap'],
 '飞踢': ['Dropkick'],
 '飞踹': ['Dropkick'],
 '飞身踢': ['Dropkick'],
 '飞镖': ['Flechettes'],
 '香蕉皮': ['Clumsy'],
 '骨折': ['Crush_Joints'],
 '骰子': ['Calculated_Gamble'],
 '魔丸': ['Dualcast'],
 '魔方': ['Mental_Fortress'],
 '鱼香': ['After_Image'],
 '黑拥': ['Dark_Embrace'],
 '黑暗之拥': ['Dark_Embrace'],
 '黑暗镣铐': ['Dark_Shackles'],
 '黑球': ['Darkness', 'Doom_and_Gloom', 'Rainbow'],
 '🌀': ['Dazed'],
 '🌈': ['Foreign_Influence', 'Rainbow'],
 '🌠': ['Wish'],
 '🌩️': ['Storm'],
 '🍃': ['Inner_Peace'],
 '🍗': ['Feed'],
 '🎒': ['Prepared'],
 '🎯': ['Accuracy', 'Bullseye'],
 '🎲': ['Calculated_Gamble'],
 '🎳': ['Bowling_Bash'],
 '🎵': ['Battle_Hymn'],
 '🏃': ['TURBO'],
 '🏃\u200d➡️': ['TURBO'],
 '🏆': ['Pride'],
 '🏳\u200d🌈': ['Rainbow'],
 '🐯': ['Rushdown'],
 '👁️': ['Foresight', 'Go_for_the_Eye', 'Terror', 'Third_Eye'],
 '👋': ['Wave_of_the_Hand'],
 '👥': ['Doppelganger'],
 '👻': ['Wraith_Form'],
 '👼': ['Apotheosis'],
 '💀': ['Bouncing_Flask', 'Deadly_Poison', 'Envenom', 'Exhume', 'Offering'],
 '💉': ['J.A.X.'],
 '💢': ['Anger'],
 '💣': ['The_Bomb'],
 '💪': ['Flex', 'Limit_Break'],
 '💯': ['Lesson_Learned'],
 '📖': ['Lesson_Learned', 'Study'],
 '🔁': ['Equilibrium'],
 '🔍': ['Seek'],
 '🔔': ['Curse_of_the_Bell'],
 '🔗': ['Dark_Shackles', 'Normality'],
 '🔥': ['Fiend_Fire', 'Fire_Breathing'],
 '🔧': ['Self_Repair'],
 '🔨': ['Bash', 'Bludgeon'],
 '🕯️': ['Devotion'],
 '🖐️': ['Exhume'],
 '🗡️': ['Ritual_Dagger'],
 '😡': ['Crescendo', 'Eruption', 'Indignation', 'Simmering_Fury', 'Tantrum'],
 '😤': ['Steam_Barrier'],
 '😱': ['Madness'],
 '😵': ['Blind'],
 '🙏': ['Pray'],
 '🛡️': ['Barricade', 'Defend_(Ironclad)'],
 '🤔': ['Concentrate'],
 '🤝': ['Burning_Pact'],
 '🤯': ['Empty_Mind', 'Enlightenment'],
 '🤸': ['Acrobatics'],
 '🥶': ['Fear_No_Evil', 'Inner_Peace', 'Meditate', 'Tranquility', 'Vigilance'],
 '🦋': ['Metamorphosis'],
 '🧛': ['Bite'],
 '🧩': ['Insight'],
 '🧲': ['Magnetism'],
 '🩸': ['Blood_for_Blood', 'Bloodletting'],
 '🩹': ['Bandage_Up'],
 '🪙': ['Just_Lucky']}
